---
name: Build

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Build (Windows)
        if: startsWith(matrix.os, 'windows')
        run: |
            call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
            // rem # patch -p0 < vs2019patch.patch
            set QTDIR="d:\a\qt_4_8_7_win\qt_4_8_7_win\bin"
            set PATH=%QTDIR%\bin;%PATH%
            patch -p1 < qt-4.8.7-win.patch
            // rem yes yes | configure -nomake examples -nomake demos -opensource -platform win32-msvc2015
            // rem nmake
        shell: cmd

